name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Restore pip/pipenv cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/virtualenvs
          key: pip-${{ runner.os }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install pipenv
        run: pip install pipenv
      - name: Install deps (dev)
        run: pipenv install --dev
      - name: Lint
        run: pipenv run lint
      - name: Test
        run: pipenv run test

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: lint_test
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t mp-backend:latest .
