name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  test_lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      
      - name: Create venv with Python 3.10
        run: pipenv --python 3.10

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test

      - name: Run linter
        run: pipenv run lint

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test_lint
    if: ${{ success() }}
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t mp-backend:latest .
