name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - 'starter/frontend/**'
      - '.github/workflows/frontend-cd.yml'
  workflow_dispatch:

concurrency:
  group: frontend-cd
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --watchAll=false

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=http://localhost:5000 \
            -t ${{ vars.FRONTEND_ECR }}:${{ env.IMAGE_TAG }} \
            starter/frontend

      - name: Push image
        run: docker push ${{ vars.FRONTEND_ECR }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.4.1'

      - name: Set image and apply
        working-directory: starter/frontend/k8s
        run: |
          kustomize edit set image frontend=${{ vars.FRONTEND_ECR }}:${{ env.IMAGE_TAG }}
          kustomize build | kubectl apply -f -
          kubectl rollout status deployment/frontend
